// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLYPlh4lGy89g57tNc8ovq_9Xr_fC4fE',
    appId: '1:172159182979:web:8ed43f9898a47cddca93b6',
    messagingSenderId: '172159182979',
    projectId: 'shopify-pricesync-v2',
    authDomain: 'shopify-pricesync-v2.firebaseapp.com',
    storageBucket: 'shopify-pricesync-v2.firebasestorage.app',
    measurementId: 'G-BCD8R0CZZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1eGzG0yIuDuGIBW0GK6CxKprUaWAI15M',
    appId: '1:172159182979:android:d1ad93fd5af78d7aca93b6',
    messagingSenderId: '172159182979',
    projectId: 'shopify-pricesync-v2',
    storageBucket: 'shopify-pricesync-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYaUsI6vx_pG6eOYJZ_ymY4pi4jbJMlxE',
    appId: '1:172159182979:ios:8eef191c12597af3ca93b6',
    messagingSenderId: '172159182979',
    projectId: 'shopify-pricesync-v2',
    storageBucket: 'shopify-pricesync-v2.firebasestorage.app',
    iosBundleId: 'com.example.shopifyPricesyncV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYaUsI6vx_pG6eOYJZ_ymY4pi4jbJMlxE',
    appId: '1:172159182979:ios:8eef191c12597af3ca93b6',
    messagingSenderId: '172159182979',
    projectId: 'shopify-pricesync-v2',
    storageBucket: 'shopify-pricesync-v2.firebasestorage.app',
    iosBundleId: 'com.example.shopifyPricesyncV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLLYPlh4lGy89g57tNc8ovq_9Xr_fC4fE',
    appId: '1:172159182979:web:c3107d8a34b884c2ca93b6',
    messagingSenderId: '172159182979',
    projectId: 'shopify-pricesync-v2',
    authDomain: 'shopify-pricesync-v2.firebaseapp.com',
    storageBucket: 'shopify-pricesync-v2.firebasestorage.app',
    measurementId: 'G-N67VLJDDW8',
  );
}
