import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'services/db_services.dart';
import 'screen/splash_screen.dart';
import 'screen/analytics_dashboard_screen.dart'; // ✅ Added import
import 'firebase_options.dart'; // make sure this file exists (auto-generated by Firebase CLI)

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  bool initError = false;
  try {
    // 🔹 Initialize Firebase first
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // 🔹 Then initialize Hive (for local logs)
    await Hive.initFlutter();
    await DBService.initDB();

    debugPrint("✅ Firebase & Hive initialized successfully");
  } catch (e) {
    debugPrint("❌ Initialization failed: $e");
    initError = true;
  }

  runApp(MyApp(initError: initError));
}

class MyApp extends StatelessWidget {
  final bool initError;
  const MyApp({super.key, this.initError = false});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Shopify PriceSync',
      theme: ThemeData(
        primarySwatch: Colors.purple,
        scaffoldBackgroundColor: const Color(0xFFF8EDEE),
      ),
      home: initError ? const InitErrorScreen() : const SplashScreen(),
    );
  }
}

class InitErrorScreen extends StatelessWidget {
  const InitErrorScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red.shade50,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.error, color: Colors.red, size: 70),
            const SizedBox(height: 20),
            const Text(
              "Initialization Failed!",
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 10),
            ElevatedButton(
              onPressed: () {
                Navigator.pushReplacement(
                  context,
                  MaterialPageRoute(builder: (_) => const SplashScreen()),
                );
              },
              child: const Text("Retry"),
            ),
            const SizedBox(height: 20),
            // ✅ Direct Access to Analytics Dashboard (for testing or future use)
            OutlinedButton.icon(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const AnalyticsDashboardScreen(),
                  ),
                );
              },
              icon: const Icon(Icons.analytics, color: Colors.deepPurple),
              label: const Text(
                "Open Analytics Dashboard",
                style: TextStyle(color: Colors.deepPurple),
              ),
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Colors.deepPurple),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
